### ISSUE TITLE
Migrate doesn't aware that new previous versions are added if any

### ISSUE THREAD

**Issue by ysaakpr** [golang-migrate/migrate#102]
Since migrate isn't storing the list of executed migration script, it cant say in case a new migrations script added to the source and which is of an older version. Here is the scenario

Currently version applied to db : 100
While in a code pull a new version 90 came to the repo

But when I run migrate it says no changes, because there is no awareness of applied migrations by this system

This is happening in a multi member env where multiple people are parallelly working, and migrations are not failing.

May be its good to store all the applied migrations in the migrations table and check for validity between source and current state and make them to force in case they cant apply automatically or warn the user they have

**Comment by dhui** [comment]
See also: https://github.com/golang-migrate/migrate/issues/65#issuecomment-401002644

Because migrate treats migrations as opaque data blobs, it can't automatically resolve any conflicts between migrations. By using strictly monotonically increasing version numbers, migrate doesn't need to track a list of all previously run migrations. Keep in mind that the order in which migrations are run are important and any conflicts need to be resolved with a new migration. In git terms, you'd need to resolve conflicts via rebase instead of merge.
Currently, migrate assumes that migration sources are never modified, but a MANIFEST file containing the hashes of all sources could be used to detect this case.

Any change to fix this may take a while to get correct in migrate, so if you need a short term solution for your team, I'd write a simple bash script that detects conflicting migration versions and run that in CI.

**Comment by dhui** [comment]
> But really prefer to store this information in the database migration schema, because we can even know what all are the different migrations applied to database without checking the code.

Do you have a need/use-case for keeping a history of applied migrations in the DB? Doing so involves a change in the DB driver interface and will complicate **ALL** of the DB drivers.

As I mentioned in my other comment, DB migration conflicts should be caught in the dev workflow and not in the integration environment and hopefully not the production one.

**Comment by ysaakpr** [comment]
the devops team can easily communicate by looking at the migration db to see the applied versions, forcefully applied version, migration time, meta informations like file hash at the time

And when the datastore we dealing with can store data in much organised way why do we stick to files for storing the information.

I agree that its developer problem to fix the issues and should find such migration conflicts in the dev time.. But having data in the db will give us more insights to the migration history by just accessing the database, and not the code base. which will become handy in times

**Comment by dhui** [comment]
> the devops team can easily communicate by looking at the migration db to see the applied versions, forcefully applied version, migration time, meta informations like file hash at the time

Some of that information can be provided via a MANIFEST file. But I don't think that all of that information is necessary. I think there's a difference in mindset/approach to this problem.

Migrations are mastered by the migration file source, not the db. e.g. If you're subscribe to the philosophy of running migrations to sync your app data schema state to the db, then the source of truth is your app.
So the correct place to detect conflicts are at the migration source, not downstream in the db after the conflicting migrations have been applied. Wouldn't you rather catch the the conflict earlier rather than later? e.g. during code review and CI instead of during integration testing
Think along the lines of preventing the conflicts from occurring during a migration run instead of forcing a migration to run through conflicts. e.g. the devops team shouldn't ever have to deal with conflicting migrations b/c with the proper processes and tools in place, they should all be caught by the dev team.

If you don't subscribe to the philosophy where the app data scheme is the source of truth, then try [sqlboiler](https://github.com/volatiletech/sqlboiler) or [xo](https://github.com/xo/xo), which treat your db schema as the source of truth and generates Go code to interact w/ it.

> And when the datastore we dealing with can store data in much organised way why do we stick to files for storing the information.

This is not a convincing argument. Just because something can be done, doesn't mean it should be.

**Comment by ysaakpr** [comment]
1. We are not using this library as a go library, we are trying to build a language/platform agnostic migration framework where all teams can follow standard tools to setup migrations of different data stores in same way. So we mostly depending on the binary command line.
2. We need a very simple and minimal command line tool with less platform deps(We will use this binary as a init container to run the migrations in a k8s env), and that should not add extra difficulties for dev team to understand how to do migrations, and the tool understanding.
3. I perfectly agree that, keeping these details in a source file will help to resolve the problems at the merge time. But given that migrate can have different source repo for code and migration which in turn leads that the devops team may not be aware where is the  migrations files stored for each of the apps they are managing. In case of an issues, to see the difference in migrations applied to database and migrations in the source, keeping these informations in the datastore will help in better quality of inter team communication. But regardless of from what source the migration applied, the devops team have standard way to see the applied migrations and its meta informations. Which add cleanliness to the migration framework behaviour in a big and multi team - with devops environment. 

2. End of having more granular details always help in communication in a bigger environment.

**Comment by dhui** [comment]
> But given that migrate can have different source repo for code and migration which in turn leads that the devops team may not be aware where is the migrations files stored for each of the apps they are managing.

I strongly recommend against this approach if you use migrate. As I mentioned before, you must subscribe to the philosophy of your app being the source of truth for your data schema/layout when using migrate. e.g. all db schema changes should originate from the app's migrations

**Comment by stephenchu** [comment]
@dhui i want to chime in on this ticket (and I have already read #65).

Politely, if your viewpoint on this topic hasn't changed, please consider _deprecating_ the feature of using timestamp as a migration filename prefix. By using a timestamp prefix, I believe it effectively eliminates the possibility of preventing someone from merging into master branch a bad migration file that has a prefix before/less-than the `schema_migrations` table current version (in production).

When using plain old sequence number prefix, at least I can write a test to detect whether there are 2 (or more) migration up files that has the same sequence number, and fail the test, and avoid the PR from merging.

When using timestamp prefix, the files are almost always unique. How would you suggest me to avoid one such bad PR from merging onto master, when prior to merging there is no visibility into what the current production `schema_migrations` table state is?

Really appreciate some wisdom here to catch problems like this early on in pre-production SDLC. Thank you 🙏 .

**Comment by dhui** [comment]
@stephenchu Given the current limitations of `migrate`, you're better off using sequence numbers for your migration versions precisely for the reason you stated:

> When using plain old sequence number prefix, at least I can write a test to detect whether there are 2 (or more) migration up files that has the same sequence number, and fail the test, and avoid the PR from merging.

Ideally, `migrate` would support detecting conflicting migrations using a `MANIFEST` file stored with the migration source, but that hasn't been designed or implemented yet.

> Really appreciate some wisdom here to catch problems like this early on in pre-production SDLC.

In the short-term, you can write tooling to check for modifications of migrations since that should be rare or be super vigilant in PRs, but that doesn't scale. In the long-term, `migrate` needs to be able to detect conflicting migrations (probably via a MANIFEST file unless people have a better idea). Would you be able to help out with any such efforts?
