### ISSUE TITLE
Microsoft SQL Server Support

### ISSUE THREAD

**Issue by bwiggs** [golang-migrate/migrate#160]
I may take a stab at adding database support for MSSQL Server.

So far the only issue I've had is it seems the dktest package doesn't currently support non dockerhub repositories. Microsoft hosts their SQL Server images on their own repo @ mcr.microsoft.com/mssql/server:latest. I'll follow up with the dktest team on adding support this, hopefully I'm misinterpreting their documentation.

Would this be a welcome PR? Anything else I should know before heading down this path?

**Comment by dhui** [comment]
Adding support for MSSQL would be appreciated!

There's a public developer MSSQL docker image [here](https://hub.docker.com/r/microsoft/mssql-server-linux/), which is free to use for testing/development purposes.
I used it in [satomic](https://github.com/dhui/satomic/blob/master/savepointers/mssql/mssql_test.go). Make sure you add similar comments regarding the licensing that I did in satomic.

**Comment by bwiggs** [comment]
Thanks @dhui! I'll check this out and see where I get.

From [hub.docker.com/r/microsoft/mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/):

> We are moving to mcr.microsoft.com where you can pull SQL Server 2017 on Linux containers as well as SQL Server 2019 preview containers. SQL Server 2019 preview containers will only be available on mcr.microsoft.com. Overtime we will only publish to mcr.microsoft.com/mssql/server and eventually deprecate microsoft/mssql-server-linux.

So for now I'll get this working with the images they still have on Dockerhub, but this might break in the future.  I've added dhui/dktest#1: to track being able to specify alternate repository locations in tests. I'll switch to the Microsoft's MCR depending on how that issue goes .

**Comment by maxekman** [comment]
Would love to get support for MSSQL!

**Comment by nathan-c** [comment]
@bwiggs how was progress on this?

**Comment by bwiggs** [comment]
Hey all,

I've got a working mssql migration over on https://github.com/EvoSure/migrate/tree/mssql but i haven't written any tests for it.

I've had to jump on some other things before I can get back to this. The current version we have has been working for us until we can jump back over to it and fill out tests and edge cases. At this time it isn't ready for a PR back to origin or for your production needs.

If anyone would like to help contribute to this in the mean time, I'm open to PRs. I could use some help bringing in the latest changes from origin and filling in tests.

**Comment by nathan-c** [comment]
Had a bit of time to take a look. Pull request submitted #222

**Comment by bwiggs** [comment]
Fantastic! Thanks @nathan-c

**Comment by dhui** [comment]
MS SQL Server is officially supported in [v4.4.0](https://github.com/golang-migrate/migrate/releases/tag/v4.4.0)

**Comment by dhui** [comment]
We will be removing official support for MS SQL Server since the docker images are [breaking builds](https://github.com/golang-migrate/migrate/issues/254) and I don't have the expertise or time to fix the issue.

If you'd like MS SQL Server to be supported again, please try to get the builds passing again.

**Comment by dhui** [comment]
Builds are currently failing due to the MS SQLServer Docker container not starting up...
It seems that there are a few [open issues related](https://github.com/microsoft/mssql-docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Operation+not+permitted+) to what we're experiencing. I have a [branch](https://github.com/golang-migrate/migrate/compare/master...dhui:debug_sqlserver_tests?expand=1) with extra container logging enabled (for debugging) and [failed attempts](https://travis-ci.org/dhui/migrate/branches) to fix the issue if anyone wants to help fix the issue.

**Comment by dhui** [comment]
Turns out CTP3.2 is the version that broke tests, so I'm pinning tests against CTP3.1 and we'll retain MS SQL Server support!

**Comment by dhui** [comment]
Builds are passing now: https://travis-ci.com/golang-migrate/migrate/builds/123671208
