### ISSUE TITLE
Postgres driver does not correctly read result of unlock call

### ISSUE THREAD

**Issue by andremarianiello** [golang-migrate/migrate#168]
**Describe the Bug**
The postgres driver calls 'SELECT pg_advisory_unlock($1)'. This function returns a bool. `ExecContext` is used, but that is only supposed to be used for queries that return no result. Since this query return a single row, `QueryRowContext` should be used instead. Additional handling could be done in the case that the unlock call fails (returns `f`).

**Additional Context**
I noticed that creating a Migrate object and then running `Up` left a connection hanging around, and the query it was running was `SELECT pg_advisory_unlock($1)`. Then I saw that `ExecContext` was being used to run that query instead of `QueryRowContext`. I assumed this was the issue, and that using `QueryRowContext` instead would cause the connection to be freed. This is not the case. The issue was I was not calling `Close` on the migrate object. However, I do believe this is still technically not being handled correctly, so I am filling this issue just in case.

**Comment by dhui** [comment]
Sounds like your issue was due to the missing `Close()` call, which would have left the session open, thus holding the lock.

`Exec()` is the correct method to call as `pg_advisory_lock()` has a `void` [return type](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADVISORY-LOCKS)

**Comment by andremarianiello** [comment]
This issue is about pg_advisory_unlock which returns a boolean, not pg_advisory_lock. Please consider reopening this issue.

**Comment by dhui** [comment]
I looked at the postgres driver's `Unlock()` implementation and to preserve backwards compatibility, no change should be made.
e.g. a `nil` error should be returned if `pg_advisory_unlock()` returns false to mirror the existing behavior of `if !p.isLocked { return nil }`

In other words, this is the expected behavior:
```golang
var d postgres.Postgres // instance of postgres DB driver
d.Lock() // succeeeds
d.Unlock() // should return nil error
d.Unlock() // 2nd call should also return nil error
```

**Comment by andremarianiello** [comment]
When you say "no change should be made", you mean we should behave the same way, regardless of the return value, right? You don't mean we should continue to never read the return at all?

**Comment by dhui** [comment]
The return value of `Unlock()` does not depend on the result of `pg_advisory_unlock()` so why bother getting it?

**Comment by andremarianiello** [comment]
I am worried about the postgres server retaining the result until the client reads it, but I can't say that I am a postgres expert. I don't know the full ramifications of not handling the result.

**Comment by dhui** [comment]
> I am worried about the postgres server retaining the result until the client reads it

That's not an issue.
See the [docs](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS) regarding session-level advisory locks.
