### ISSUE TITLE
Cannot install migrate using glide

### ISSUE THREAD

**Issue by fabianTMC** [golang-migrate/migrate#180]
**Describe the Bug**
Cannot install migrate using glide

**Steps to Reproduce**
1. Run `glide get github.com/golang-migrate/migrate`

**Go Version**
go version go1.11.2 linux/amd64

**Stacktrace**
```sh
[INFO]  Resolving imports
[INFO]  --> Detected semantic version. Setting version for github.com/golang-migrate/migrate to v4.2.5
[ERROR] Error scanning github.com/golang-migrate/migrate/v4/database: cannot find package "." in:
        /home/fabian/.glide/cache/src/https-github.com-golang-migrate-migrate/v4/database
[ERROR] Error scanning github.com/golang-migrate/migrate/v4/source: cannot find package "." in:
        /home/fabian/.glide/cache/src/https-github.com-golang-migrate-migrate/v4/source
[ERROR] Error scanning github.com/golang-migrate/migrate/v4: cannot find package "." in:
        /home/fabian/.glide/cache/src/https-github.com-golang-migrate-migrate/v4
[INFO]  --> Fetching updates for gopkg.in/yaml.v2
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports
```

**Comment by dhui** [comment]
See: https://github.com/golang-migrate/migrate#supported-major-versions

Since you're using Go 1.11+ and migrate v4, I'd use modules if possible.
`dep` is used to manage dependencies for migrate v3 and Go 1.10.x. However, since Go 1.12 was [just released](https://blog.golang.org/go1.12) and we only support [supported version of Go](https://golang.org/doc/devel/release.html#policy), Go 1.10.x support will be dropped soon. e.g. won't be backporting security fixes.

You can try using migrate v3 with glide, but migrate won't officially support that.
My guess is that you're hitting an issue similar to: https://github.com/golang-migrate/migrate/issues/103

**Comment by dhui** [comment]
Closing due to lack of response
