### ISSUE TITLE
Automatic rollback on migration fail

### ISSUE THREAD

**Issue by mcandre** [golang-migrate/migrate#183]
Please attempt to run the down migration and get back to a clean state when an up migration fails. Currently, golang-migrate just complains "Dirty database".

**Comment by dhui** [comment]
Leaving the the DB in a dirty state when a migration fails to apply is done by design.
`migrate` doesn't know how the failed migration was written or what it was attempting to do when it failed, so `migrate` can't be sure that the respective down migration is safe to run for a failed migration. e.g. it's best for a human to inspect the state of the system and determine the best way to fix things

**Comment by pwaterz** [comment]
What do you think about adding an options for this? For me personally I would prefer it just try to do the migration again is the app is restarted. I work in a large AWS env where I don't have direct access to the databases. So when something gets in this state I have to involve a DBA which is time consuming. To me it seem bad that an app can just get stuck in a broken state and the only way to fix it is manual intervention.

**Comment by dhui** [comment]
You can implement retries whether you're using `migrate` as a Go library or the CLI.
As mentioned earlier, it's unsafe for `migrate` to do this automatically. Adding such an option does not provide additional value over fixing the issue yourself. e.g. forcing and re-running the migration.
Remember, you can always make a bad situation worse if you don't know what you're doing.

**Comment by pwaterz** [comment]
How would one implement retries? From what I could tell you can't execute the migrations again because it first check if it's in a dirty state. I've written 100's of migration in my day and I've never ran into an issue where the 'migration' was dirty. If there was an issue we fixed the issue and rerun the migration. I might get some flack for this, but Drupal implements their migrations this way and there are tens of millions of drupal sites out there that never have had this issue.

**Comment by dhui** [comment]
> How would one implement retries?

By forcing the schema version to the last known good version, which resets the dirty state. e.g. marks it as clean. The "last known good version" is most likely the migration immediately preceding the failed one. Once the dirty state has been reset, then you can re-run your migrations. As mentioned before, doing this without any context is **extremely dangerous** and **not recommended**. To safely fix any failed migration, you need to understand the failure and take the appropriate corrective actions which cannot be done in a generally for all RDBMSs.

For more info around fixing/forcing dirty migrations, see [this](https://github.com/golang-migrate/migrate/blob/master/FAQ.md#what-does-dirty-database-mean) and [this](https://github.com/golang-migrate/migrate/blob/master/GETTING_STARTED.md#forcing-your-database-version)

**Comment by pwaterz** [comment]
Can you elaborate on why you think it's extremely dangerous?

**Comment by dhui** [comment]
> Can you elaborate on why you think it's extremely dangerous? I'm not trying to troll you, just trying to understand the problem.

👍 

> If I was using the CLI it would still require manual investigation

This is still true for migrations run via the Go library. Any migration failure requires an investigation. e.g. your migrations may run in your dev and test environments but fail in production due to configuration differences

Correctly and automatically fixing migrations is akin to solving the [halting problem](https://en.wikipedia.org/wiki/Halting_problem).
There's no way to know why a particular migration or SQL statement failed.
In your example, DB creation could have failed due to permissions for the DB user being changed, the DB user was removed, the default schema being changed, etc
The solution for each of these different situations will be different. Not every migration is retry-able, esp if it's not wrapped in a transaction.

**Comment by pwaterz** [comment]
I did come up with this in my code as a work around

```
err = m.Up()
dirtyErr, ok := err.(migrate.ErrDirty)
if err != nil && err != migrate.ErrNoChange && err != migrate.ErrNilVersion && err != migrate.ErrLocked && !ok {
	panic(fmt.Sprintf("Error occurred running migrations: %v", err))
}

if ok {
	log.Error("Migration is dirty, forcing rollback and retrying")
	m.Force(dirtyErr.Version - 1)
	err = m.Up()
	if err != nil && err != migrate.ErrNoChange && err != migrate.ErrNilVersion && err != migrate.ErrLocked {
		panic(fmt.Sprintf("Error occurred running migrations: %v", err))
	}
}
```

**Comment by pwaterz** [comment]
Halting problem is an interesting philosophical idea, but I prefer real world examples. I agree not all are retry-able but I feel like more often than not they are.  In general migrations are creating tables, or altering them. If you have something that requires transactions or that is more complex, I think there are better ways to solve that. I.e. a cli for your app.

**Comment by sn0rk64** [comment]
@pwaterz 

I found a better solution, especially if you use timestamps instead of sequences. 

```go
    dirtyErr := &migrate.ErrDirty{}
    if errors.As(err, dirtyErr) {
		logrus.Errorf("Failed to migrate the version [%d]: %v\n Trying to rollback it...", dirtyErr.Version, err)

		prevVersion, err := src.Prev(uint(dirtyErr.Version))
		if errors.Is(err, os.ErrNotExist) {
			return true
		}
		if err != nil {
			logrus.Errorf("Failed to find a previous migration version: %v", err)
		}

		logrus.Infof("Forcing migration to the version [%d]", prevVersion)

		err = mg.Force(int(prevVersion))
		if err != nil {
			logrus.Errorf("Failed to force migration to the version [%d]: %v", prevVersion, err)
		}
    }
```
