### ISSUE TITLE
Add redo command to CLI

### ISSUE THREAD

**Issue by skateinmars** [golang-migrate/migrate#198]
**Is your feature request related to a problem? Please describe.**

I'm considering migrating away from goose to this tool (which has lots of features like locking, split files for migrations...), but goose has a nice command called `redo` that re-runs the latest migration, which is useful during development.

**Describe the solution you'd like**
I guess `redo` could take an optional argument `N` to specify how far migrate should go back?

**Describe alternatives you've considered**
Up/Down commands obviously work :)

**Comment by dhui** [comment]
Thanks for the suggestion!

What are your usecases for a redo command? e.g. in what scenarios would you find the command useful?

I'm hesitant to add a redo command to the CLI since the behavior of such a command is not clear.
1. Is it safe to re-run a migration? e.g. migrations **should** be idempotent but may not be
1. Does running down and up make sense? What happens if there's no down migration (they're not required) or if the down migration fails?
1. If the last migration (both up and down) didn't successfully apply, should redo force it to the "previous" migration? Currently, there's no way for migrate to know which migration failed to apply (e.g. direction isn't tracked by any DB drivers right now) and where the migration failed

Given the issues listed above, it's safer to err on the side of caution and not implement redo unless there's a compelling usecase for it. For now, I'd use the simpler commands since migrations are free-form today and you need a human to help you navigate/troubleshoot any issues. A redo command would probably make the situation more confusing and harder to debug.

**Comment by skateinmars** [comment]
Thanks for the feedback, those are really good points!

To be honest I don't have much of a compelling case for a redo command besides "a convenience to make sure your migration can be rollbacked and reapplied properly"
But this indeed probably doesn't warrant the addition of a command.

Closing this for now :heavy_check_mark:
