### ISSUE TITLE
Google CloudSQL (proxy)

### ISSUE THREAD

**Issue by hazcod** [golang-migrate/migrate#205]
**Is your feature request related to a problem? Please describe.**
I am currently using go-pg, which supports connecting to CloudSQL (postgresql) via the CloudSQL proxy. (if running locally)
However, I am unable to provide the go-pg instance to migrate.

**Describe the solution you'd like**
I'd eihter like CloudSQL (proxy) support or the possibility to pass my instance of go-pg. (*pg.DB)

**Describe alternatives you've considered**
/

**Additional context**
*pg.DB does not implement database.Driver

My current database init code:
```
func InitDatabase(instanceUrl string, user string, password string, database string) *pg.DB {
	return pg.Connect(&pg.Options{
		Dialer: func(network, addr string) (net.Conn, error) {
			return proxy.Dial(instanceUrl)
		},
		User: user,
		Password: password,
		Database: database,
	})
}
```

**Comment by dhui** [comment]
Any reason why you can't connect using the existing postgres db driver?
You migrations will need to be written in SQL anyways which is driver agnostic.

Generally, I wouldn't recommend creating an instance of `Migrate` using an instance of the db driver since `Migrate.Close()`, which should be called once you're finished interacting with migrations, will close both source and database drivers, so you wouldn't be able to re-use the db driver anyways.
