### ISSUE TITLE
Env var in migration files

### ISSUE THREAD

**Issue by GreenLamantin** [golang-migrate/migrate#239]
Now I integrate ClickHouse in our project with Golang backend. ClickHouse has driver for taking data directly from Kafka, but I need to create ClickHouse table with Kafka driver and specify queue connection address. For local env in it something like `localhost:9092`.
```
CREATE TABLE IF NOT EXISTS queue
(
    some_field String,
) ENGINE Kafka('localhost:9092', 'queue', 'group1', 'JSONEachRow');
```
But I can't use this address in migration file, because production address is different. 
Is it possible to use e.g. env vars and write something like `... ENGINE  Kafka('$ADDRESS', 'queue', ...`, or other parameterization?

**Comment by dhui** [comment]
Parsing migrations goes against the project's [philosophy](https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md#migration-content-format).

It's unfortunate that the params for connecting Kafka to Clickhouse must be made in the table creation statement. I guess reading such params from the connection config doesn't make much sense either.

I see a few workarounds for this but they all have their issues:
1. Use a proxy like [Envoy](https://www.envoyproxy.io/). Keep in mind that doing so increases your operational burden.
1. Use separate migrations for different environments. This not only increases your operational burden (by a bit) but it also makes it easier to introduce differences between you environments.
1. Use template system/language for your migrations and resolve/render the templates before being passing them to `migrate`. See: https://github.com/golang-migrate/migrate/issues/20 and https://github.com/golang-migrate/migrate/issues/15. I'm hesitant to support templates in `migrate` because escaping with all of the DBs we support would be a nightmare.
