### ISSUE TITLE
SOURCE and DATABASE variables are ignored when running tests

### ISSUE THREAD

**Issue by klingtnet** [golang-migrate/migrate#273]
**Describe the Bug**
The `SOURCE` and `DATABASE` variables are ignored when running tests through `make`.

**Steps to Reproduce**

```sh
$ make test-short SOURCE='file' DATABASE='mysql'
```

This runs all tests against all databases.

**Expected Behavior**

```sh
$ go test ./database/mysql/... ./source/file/...
ok  	github.com/golang-migrate/migrate/v4/database/mysql	95.552s
```

**Migrate Version**

```sh
$ git describe --tags --always
v4.6.0
```

**Loaded Source Drivers**

Not applicable.

**Loaded Database Drivers**

Not applicable.

**Go Version**

```sh
$ go version
go version go1.12.8 linux/amd64
```

**Stacktrace**

Not applicable.

**Additional context**

```sh
$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ uname -a      
Linux m604 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```

**Comment by dhui** [comment]
Thanks for the report! This broke when resolving this issue: https://github.com/golang-migrate/migrate/issues/2

One option to fix is to add build flags to all the DB and source tests. We shouldn't add build flags to the non-test files, otherwise we'll break dependencies.

Any other suggestions for a fix?

**Comment by klingtnet** [comment]
I haven't had a deep look in the code, but what about evaluating the environment variables before each test and return if the test is not in the scope?

**Comment by dhui** [comment]
I'm ok leaving `DATABASE` and `SOURCE` as CLI build only make variables unless someone wants to go through the trouble of adding build flags to tests. I don't think there's much value in doing this and makes writing tests more onerous since it adds yet another thing to do...

Adding env var checks to the code is even more work and fragile since each test function would need this.
