### ISSUE TITLE
Dirty database version 1. Fix and force version

### ISSUE THREAD

**Issue by duyanghao** [golang-migrate/migrate#282]
the error appears as below when migrate timeout:
```
Dirty database version 1. Fix and force version
```

**Steps to Reproduce**
1. do migrate timeout
2. migrate again

**Expected Behavior**
migrate again could automatically solve this problem and do migrate normally.

**Comment by dhui** [comment]
Timeouts may occur and the correct fix is not obvious, so user intervention is necessary.
e.g. The migration could have never applied, partially applied, or fully applied

**Comment by duyanghao** [comment]
@dhui How to fix `Dirty database status`? Is there any documents for this?

**Comment by anihex** [comment]
@duyanghao Force to a previous version and then run "up" again.

So if you get an error in version 10, fix the error and then force it to version 9. Afterwards you can migrate again.

**Comment by duyanghao** [comment]
> @duyanghao Force to a previous version and then run "up" again.
> 
> So if you get an error in version 10, fix the error and then force it to version 9. Afterwards you can migrate again.

@anihex Could you please give an example as described above?

**Comment by bkakadiya42** [comment]
Maybe I am missing something here. If we are running migrations within a transaction, why do we need to mark the database as dirty? Asking this because it slows down rapid iterations on the migration if the developer has to force after every failure, and when it is the very first migration you can't force it to the version `000000`

**Comment by ann-kilzer** [comment]
@bkakadiya42 I had the same issue, ended up resetting my entire DB to start clean and then fix my migration file. Hope that helps!

**Comment by warent** [comment]
It helps bandaid the problem, but it still leaves the question open why a failed transaction makes the database dirty. This must be a bug. The "force" UX is also very user hostile.

**Comment by tiagosimao** [comment]
> Maybe I am missing something here. If we are running migrations within a transaction, why do we need to mark the database as dirty? Asking this because it slows down rapid iterations on the migration if the developer has to force after every failure, and when it is the very first migration you can't force it to the version `000000`

Spot on. Error on first migration seems irrecoverable through **migrate**'s interface. I will hack away and drop the schema_migrations table (if dirty && Version==1) but this is clearly an abstraction violation.
Also, all of this is just silly when using Postgres (or any other db with transaction support in schema changes for that matter)

Didn't understood why the issue is marked as resolved, even the initial question refers to error on version 1 but all answers just seem to ignore that detail. Maybe I'm missing something as well. The docs don't seem to scratch this itch tough.

Some possible ways this lib could help the developer in tackling this corner case I can think of:
- Allowing disabling the dirty feature
- Adding method to drop schema_migrations table
- Never setting first version as dirty (probably incoherent, bad idea)

All for helping out, just didn't fully understood if this is something recognized as a problem.
I really (really) don't want to sound like a jerk, but this bug makes the lib unusable in production. I cannot have an application that out of the blue requires a human messing with the DB.

Cheerio!

**Comment by nnachefski** [comment]
I'm hitting this while deploying harbor with the kube operator.

**Comment by dhui** [comment]
>  If we are running migrations within a transaction, why do we need to mark the database as dirty?

> still leaves the question open why a failed transaction makes the database dirty

`migrate` does not enforce this (e.g. does not run all migrations in a transaction) so it cannot automatically rollback upon failure. If all of your migrations are wrapped in a transaction, then you can safely force the migration to the previous applied migration. Otherwise, you'll need to inspect the state of your db and determine how to proceed.

> The "force" UX is also very user hostile.

Even if `migrate` were able to rollback failed migration, user intervention is likely required to fix some state for a successful migration. e.g. re-running the same migration with the same starting state won't succeed
Letting the developer/sysadmin know that something is broken and requires their attention and having them acknowledge that the issue has been resolved is a good thing. However, I agree that the UX could be smoother. e.g. forcing is an extra step vs just trying to re-apply the migration

**Comment by dhui** [comment]
@nnachefski This looks like an [issue with harbor](https://github.com/goharbor/harbor/issues/12405) please continue the discussion there.
FWIW, [here](https://github.com/goharbor/harbor/tree/master/make/migrations/postgresql)'s their migrations

**Comment by mnvx** [comment]
I agree with @tiagosimao, would be great to have option
 > Allowing disabling the dirty feature

It is not handy to work with dirty migrations on production. In my case migrations executes from docker container with code. 
- This container cant start until migrations are successfully executed.
- So it is not possible to run `force` command in this container.
- I see here two ways and they are both bad (because it is a bit of hell for admins and more large time of services unavailability): 
  - adapt ci/cd processes to support `force` command,
  - change version directly in database

And my database is Posgtes where DDL queries are support transactions... So best way in my case is as said above

 > Allowing disabling the dirty feature

**Comment by xrn** [comment]
Regarding that topic also I would like to speak following: 

If my migration failed during the Down execution - let's say I would like to rollback step 5 and back to migration 4 and it crash. I will see `Dirty database version 5. Fix and force version` -  Without information regarding the direction even if I am using transactions for each migration I do not know if I should force it to version 4 (this will be a case for broken Up) or force it to version 5 (broken Down)

Currently, there is a blocker for new migrations if there is a dirty flag - thanks to that we can not mess up with db state (making several up and down). What do you think about adding information about the direction which caused that dirty state? Thanks to that user can automate forcing to correct version if is sure that is using transactions. It will be very helpful IMO

**Comment by kskenyon** [comment]
I'm trying to install Chirpstack with Postgresql on Debian Buster.  I'll be danged if I can get past this error when starting the application-server.

level=fatal msg="setup storage error: storage: migrate up error: Dirty database version 27. Fix and force version."

No idea what to do and where to do it.  This must be a common problem.  Golang related?

**Comment by joncodo** [comment]
> I'm trying to install Chirpstack with Postgresql on Debian Buster. I'll be danged if I can get past this error when starting the application-server.
> 
> level=fatal msg="setup storage error: storage: migrate up error: Dirty database version 27. Fix and force version."
> 
> No idea what to do and where to do it. This must be a common problem. Golang related?

Try this readme I made for our project: https://github.com/merico-dev/lake/blob/migrations-v2/MIGRATIONS.md

**Comment by kskenyon** [comment]
Thanks. I managed to get it working.

**Comment by buraksecer** [comment]
> the error appears as below when migrate timeout:
> 
> ```
> Dirty database version 1. Fix and force version
> ```
> 
> **Steps to Reproduce** Steps to reproduce the behavior:
> 
> 1. do migrate timeout
> 2. migrate again
> 
> **Expected Behavior** migrate again could automatically solve this problem and do migrate normally.

**If you use docker for database, you have to clear database volumes, this is working for me.**

**Comment by CodeNinjaUG** [comment]
this is what worked for me 
migrate -path db/migrations -database "postgresql://root:8bdc7axyzex@localhost:5432/simple_bank?sslmode=disable" force 1

**Comment by aksenof** [comment]
i resolved this error by inserting version with zero dirty flag in the database

in my case, my database name was "schema"

so, check the dirty version:

`SELECT * FROM schema_migrations;`

in the output i found `version` = 1 and `dirty` = 1 and `sequence` = 1666689290970899911

then i insert new data:

`INSERT INTO schema_migrations(version, dirty, sequence) VALUES (1, 0, 1666689299985899911);`

congratulations, problem solved!

note: sequence - it's a current datetime in nanoseconds, so, you need the new sequence is larger than the previous one

**Comment by dominikbraun** [comment]
Sorry to be so pointed, but if this is really by design, the design is wrong.

**Comment by idc77** [comment]
I'm getting 

Error running migration: Dirty database version 2. Fix and force version.

with v1.5.4

I have no idea what the previous version was or what to do. Help?

**Comment by cxMoonGlade** [comment]
> this is what worked for me migrate -path db/migrations -database "postgresql://root:8bdc7axyzex@localhost:5432/simple_bank?sslmode=disable" force 1
> 
> i had to even drop a database for it work.. but the force version works well

Works for me. The hint maybe close every db management application before run the migrate verbose up.
The first version is dirty, which is funny.

**Comment by tanishasri22** [comment]
@idc77 can you post redirect to the error you mentioned, if you managed to get the solution?

**Comment by tanishasri22** [comment]
> I'm getting
> 
> Error running migration: Dirty database version 2. Fix and force version.
> 
> with v1.5.4
> 
> I have no idea what the previous version was or what to do. Help?
> 
> edit: sorry, this is posted in the wrong repo... I was using shiori.


@idc77 can you post redirect to the error you mentioned, if you managed to get the solution?

**Comment by crackc0der** [comment]
Can I get more details about "Dirty database"?

**Comment by jvilhuber** [comment]
> Even if migrate were able to rollback failed migration, user intervention is likely required to fix some state for a successful migration. e.g. re-running the same migration with the same starting state won't succeed

Right: In my experience the a dev will then iterate and fix the migration, and redeploy. Given that everything needs to be automated there's really no way to recover (as stated by many others here). This design is plain broken.

What my expectation is (from experience with previous migrator frameworks): If the up migration fails, you apply the down migration, and stop, leaving the DB in a CLEAN state, so the next time it's run, we can continue where we left off (after the dev fixed the bad migration). Otherwise what's the point of down migrations? I've never seen a need for them, except for error recovery during an up-migration failure.

**Comment by m-ves** [comment]
> Thanks. I managed to get it working.
> […](#)
> Sent from my iPad
> On Jan 14, 2022, at 7:12 AM, joncodo ***@***.***> wrote: ﻿ I'm trying to install Chirpstack with Postgresql on Debian Buster. I'll be danged if I can get past this error when starting the application-server. level=fatal msg="setup storage error: storage: migrate up error: Dirty database version 27. Fix and force version." No idea what to do and where to do it. This must be a common problem. Golang related? Try this readme I made for our project: https://github.com/merico-dev/lake/blob/migrations-v2/MIGRATIONS.md — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

Dear [kskenyon](https://github.com/kskenyon), please help to fix Chirpstack migration on Debian 10.
My log is:
```
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.17649709Z" level=info msg="storage: connecting to PostgreSQL database"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.180784531Z" level=debug msg="sql query executed" args="[]" duration="334.199µs" query="lock table code_migration"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.181320388Z" level=debug msg="sql query executed" args="[migrate_to_golang_migrate 2024-09-01 15:16:36.180811569 +0000 UTC m=+0.046185572]" duration="503.908µs" query="\n\t\t\tinsert into code_migration (\n\t\t\t\tid,\n\t\t\t\tapplied_at\n\t\t\t) values ($1, $2)\n\t\t\ton conflict\n\t\t\t\tdo nothing\n\t\t"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.184714641Z" level=debug msg="sql query executed" args="[]" duration="113.005µs" query="lock table code_migration"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.185001736Z" level=debug msg="sql query executed" args="[validate_multicast_group_devices 2024-09-01 15:16:36.184784167 +0000 UTC m=+0.050158170]" duration="214.193µs" query="\n\t\t\tinsert into code_migration (\n\t\t\t\tid,\n\t\t\t\tapplied_at\n\t\t\t) values ($1, $2)\n\t\t\ton conflict\n\t\t\t\tdo nothing\n\t\t"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.185846513Z" level=info msg="storage: applying PostgreSQL data migrations"
chirpstack-application-server[20507]: time="2024-09-01T15:16:36.188005362Z" level=fatal msg="setup storage error: storage: migrate up error: Dirty database version 46. Fix and force version."
```

**Comment by yarkm13** [comment]
From this conversation I still can't figure out, is there some way to "force" when you failed in the very first migration? Or is manual db manipulation the only possibility?

**Comment by skamranahmed** [comment]
@yarkm13 If if is very first migration that has failed, then you need to clean up the db manually. It cannot be forced with the command.
