### ISSUE TITLE
Failed down migration clearing schema_migrations table?

### ISSUE THREAD

**Issue by eloff** [golang-migrate/migrate#330]
I run an up migration to version 1, then I run a down migration that fails, and even although it failed and the database is still at version 1, the schema_migrations table is cleared. I expect since the migration failed and the state of the database did not change that it should also be unchanged. Am I doing something wrong?

```
migrate 1

apimate=> select * from schema_migrations;
 version | dirty 
---------+-------
       1 | f
(1 row)

migrate -1

apimate=> select * from schema_migrations;
 version | dirty 
---------+-------
(0 rows)
```

Using version 4.7.0 and the github.com/golang-migrate/migrate/v4/database/postgres driver. The behavior happens irrespective of whether I wrap the statements in the file with BEGIN ... COMMIT. Using Go 1.13.

**Comment by dhui** [comment]
Need more info about the failure. If the SQL statement failed to successfully execute in Postgres, `migrate` should receive that error and mark the migration as dirty.

**Comment by JKKGBE** [comment]
Having same issue using migrate's CLI which was built using `go get -tags 'postgres,google_cloud_storage' -u github.com/golang-migrate/migrate/cmd/migrate`, `migrate -version` outputs `dev`.

Having a failing down migration:
- If it's numbered as 1, then `schema_migrations` table is cleared and `$?` output is 1.
- If it's numbered as 2, then `version` is set to `1` and `dirty` to `t` and `$?` output is 1.
- Numbers higher than 2, behave in the same way as 2.

On successful migrations `$?` output is 0.

Tested with three different fail points:
- dropping non-existent table,
- dropping a function that other objects depend on,
- syntax error.

Whether the migration is wrapped in a transaction or not, doesn't change the behavior.

**Comment by dhui** [comment]
@JKKGBE What `migrate` commands are you running? e.g. all commands to get to the dirty state and empty `schema_migrations` table
Are you using the latest commit from the master branch?

To be clear, the schema version table should be empty after a successful up and down migration. The only action that should succeed with a dirty/failed migration is `force`. I poked around the code and didn't see any obvious issues.

**Comment by JKKGBE** [comment]
I've updated my migrate to v4.10.0. Now `migrate -version` outputs `v4.10.0` instead of `dev` (whatever version that means - but it was installed using this method https://github.com/golang-migrate/migrate/tree/v4.10.0/cmd/migrate#unversioned).

The problem still persists. It seems the behavior is that when there's a failing `up` migration, the `version` field is set to the failing migration's number and `dirty` set to `t`. When there's a failing `down` migration, the `version` field is set to the failing migration's number - 1 and `dirty` set to `t`. 

So I'm guessing while using `migrate ... down` the decrementing process is ran in the same way every time, something along the lines of:
- if `version` > 1 then decrement by 1, else remove record from `schema_migrations` table,
- run down migration,
- if error, then set `dirty` to `t`.

So when version 1 down migration fails there's no record to set the `dirty` flag?

I am running `migrate ... up` and then `migrate ... down` and that's it. Depending which `version` is the failing migration, the behavior is as stated in my previous post.

Btw. I think https://github.com/golang-migrate/migrate/tree/v4.10.0/cmd/migrate#versioned needs fixing, as the last argument should be `.` or `$GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate`

**Comment by dhui** [comment]
> It seems the behavior is that when there's a failing `up` migration, the `version` field is set to the failing migration's number and `dirty` set to `t`.

That is correct

> When there's a failing `down` migration, the `version` field is set to the failing migration's number - 1 and `dirty` set to `t`.

That is correct but the `down` migration should only run and decrement the current version if `schema_migrations` is not dirty. If `schema_migrations` is dirty, the `down` will fail and not touch the `schema_migrations` table.

Thanks for the extra info! I think I've identified the bug. The [current logic](https://github.com/golang-migrate/migrate/blob/v4.10.0/migrate.go#L736) is to set the target version number as dirty in `schema_migrations` before running the migration and then set the target version number as clean after the migration succeeds, so any errors will leave the state as "dirty".
When migrating down from the first migration, the desire is to leave the `schema_migrations` table empty, so the [target version](https://github.com/golang-migrate/migrate/blob/v4.10.0/migrate.go#L491) is `-1`. For most DB drivers ([postgres](https://github.com/golang-migrate/migrate/blob/v4.10.0/database/postgres/postgres.go#L269) included), this means that the `schema_migrations` table will be cleared when the target version is set to dirty when running the down migration for the first migration.

### Proposed Fixes

1. Special-case running the down migration for the first migration in each DB driver. e.g. if target version is < 0 and it's dirty, insert the target version number as dirty in the `schema_migrations` table. This *should* work and be backwards compatible. e.g. It should correctly mark the last down migration as dirty before clearing after a successful run. Any issues can be resolved normally and then cleaned up by running `force 0` or `force -1`.
1. Change the `schema_migrations` table to track the currently applied migration and log the attempted migration version. e.g. use the columns `version`, `target version`, and `dirty` This change is not backwards compatible but provides more information for easier debugging. Unfortunately, we don't use `migrate` to manage the `schema_migrations` table 😞 

I'm leaning towards the first proposed fix. Thoughts?

Also, thanks for pointing out the issue w/ installing via the Go toolchain (versioned). I've fixed it here: https://github.com/golang-migrate/migrate/commit/20a1dcfe8078e402a80a9d672f410d7017d20f69

**Comment by dhui** [comment]
The first proposed fixed is now in master

**Comment by JKKGBE** [comment]
Sorry that I didn't reply, but I don't touch anything programming related on the weekends. Imo you've made the right choice for the current state of the tool.
