### ISSUE TITLE
Cant seem to create a database from migration when it doesnt exist

### ISSUE THREAD

**Issue by goapifirst** [golang-migrate/migrate#347]
**Describe the Bug**
Specifically for Postgresql driver.. not sure if this happens with other dbs, but currently I have to manually log in via psql and create every database (1 for each microservice I use this for). There doesn't seem to be a way to either a) have the first migration create the database if it does not exist or b) some way to tell the migration library to create it if it does not exist. Kind of makes it hard to automate the ability to deploy via CI to a clean sandbox if I have to manually create every database. I realize I can probably script this outside of the use of migrate, but it seems like there should be a way to allow for create the database if it doesnt yet exist without having to resort to external tools.
 
Using Go 1.13, v4 of migrate.

**Comment by dhui** [comment]
You'll need to have a db already created to use migrate since it needs to create a table to track the latest migration that's been applied and it's state.
Another option is to require that the db user used with migrate has create db permissions and use a separate db to track migrations.

For now you'll need to ensure that a db exists before using migrate.

I've updated https://github.com/golang-migrate/migrate/issues/14 to consider creating a DB.
