### ISSUE TITLE
When there are no migrations applied yet, version command returns: "error: no migration"

### ISSUE THREAD

**Issue by gadumitrachioaiei** [golang-migrate/migrate#41]
After for example, I rollback all the way, running the version command returns an error with exit code 1:
error: no migration
Why is this an error ? I wanted to assert the version from inside a bash script and this is confusing.

Also, it seems that many commands ( all ? ) write their result to stderr not stdout.

**Comment by dhui** [comment]
This is expected behavior. If you've run all down migrations, then there's no migration version to report. Keep in mind that there's the version flag which reports the version of t
e migrate CLI and the version command which reports the current version of your migrations that has been applied.

Generally, CLIs will write errors to stderr and all other output to stdout. If migrate is not doing this consistently, feel free to open a PR to fix it.

I'm not sure what you setup is, but I'd try to use Go and the migrate library to manage migrations instead of a shell script and the CLI. I'd only use shell if you're integrating w/ other shell commands since the Go API is easier to integrate with than the CLI.

**Comment by gadumitrachioaiei** [comment]
I am trying to integrate migrate in a makefile.
I could go the GO way, but would I have to redefine all the flags and handle them in my main ? Or is there an easy way to use the flags already defined in the library ?

**Comment by dhui** [comment]
Use the `Migrate` methods directly: https://godoc.org/github.com/golang-migrate/migrate#Migrate

IDK what your code is doing but you only need to call the applicable methods.

**Comment by gadumitrachioaiei** [comment]
Thanks.
