### ISSUE TITLE
Question. 

### ISSUE THREAD

**Issue by kaaquist** [golang-migrate/migrate#42]
Hi, First off thanks for a nice tool. 
I have created three `func` in go that can migrate up, down or tell me version. But I can't really seem go get my head around how to actually start, like init the whole thing. Right now I have a running instance of cockroach and I have created `init_up` and `init_down` for all schemas, data etc.
Is there a guide or document that describe the initial steps before first migration? 
I hope that you get my question, else please tell me to elaborate. Thanks.

**Comment by dhui** [comment]
You'll need to determine how and when you want to run migrations since that affects how you use the tool.

Personally, my workflow looks like this:
1. Create migrations using the CLI `create` command. This ensures that the name of the migration is compatible w/ migrate. Note, I'm using file sources for my migrations and package everything into a docker image for my API servers.
1. Use the CLI to test the up/down migration on a test DB instance. The `force` command is handy for "fixing" borked migrations.
1. Ship the API server docker image. The API server (go binary) is responsible for running migrations (up only) when starting. I rely on the db lock to prevent contention between migrations and manage migrations manually using the CLI if necessary.

**Comment by kaaquist** [comment]
Thanks for your comments. I assume that the cli will create the version table on first run? Because that is what I don't get 😀 .. Do I create it my self or does the migrate app do that?

**Comment by dhui** [comment]
Correct, the table used to track the currently applied migration is created by migrate, specifically, by the db driver.
