### ISSUE TITLE
Make '_title' in migration file name pattern optional

### ISSUE THREAD

**Issue by yongseonlee** [golang-migrate/migrate#600]
**Is your feature request related to a problem? Please describe.**
Our team would like to use migration file names without title(i.e. `0012.up.sql`) to prevent migration number conflicts in git-level. We are using it like `0012_.up.sql` as a workaround.

**Describe the solution you'd like**
How about changing the file name regex from `^([0-9]+)_(.*)\.(down|up)\.(.*)$` to `^([0-9]+)(_.*)*\.(down|up)\.(.+)$`?

**Comment by dhui** [comment]
I think it's fine to not name your migrations, but I'd recommend against this since the name should be descriptive. Or put comments describing the migration in the migration.

FYI, if you want to move forward with this change, you'll need to:
1. Fix the regex to require an underscore when a name is specified and option when it's not **AND** properly pull out the name
2. Support creating migration files without a name [via the CLI](https://github.com/golang-migrate/migrate/blob/v4.14.1/internal/cli/commands.go#L122)

**Comment by yongseonlee** [comment]
@dhui I think `1` is already satisfied with the suggested regex `^([0-9]+)(_.*)*\.(down|up)\.(.+)$`. And will it be accepted if I create a PR modifying the CLI to support migrations files without a name and with comments describing them inside them?

**Comment by dhui** [comment]
`(_.*)` incorrectly captures the name. e.g. for the string: `1_name.up.sql`, the name would be `_name` instead of `name`.

Digging a little deeper:
* What do you mean by `prevent migration number conflicts in git-level` and is this your only reason for making the migration name optional?
* How are you creating migration files?

**Comment by yongseonlee** [comment]
@dhui Oh, you're right. That regex should be fixed.

`prevent migration number conflicts in git-level` means, when I'm trying to merge my PR including migration 0010 to develop branch for example, there can be already 0010 migration created by another teammate. If the both migration files have the same name, GitHub will let me know the conflict. Otherwise, I should manually check.

And I'm creating migration files with `entgo.io`'s feature.

**Comment by dhui** [comment]
If preventing conflicts is your only motivation for this change, then wait for progress on #470 and continue using `0012_.up.sql` as your names. I'd rather not allow empty migration names so they're more descriptive.

Also, ent [doesn't use](https://pkg.go.dev/entgo.io/ent?tab=imports) this package, they have their [own](https://github.com/ent/ent/blob/v0.8.0/dialect/sql/schema/migrate.go) migration system.

**Comment by yongseonlee** [comment]
Closing this waiting for #470 .
Thanks!

(we are creating SQL queries for migration files using ent and manage the files with this project)
