### ISSUE TITLE
Trouble installing cli for postgres

### ISSUE THREAD

**Issue by aebie** [golang-migrate/migrate#67]
I am trying to try out the migrate CLI, and am running into a problem with the installation steps in the README. I run these commands:

$ go get -u -d github.com/golang-migrate/migrate/cli github.com/lib/pq
$ go build -tags 'postgres' -o /usr/local/bin/migrate github.com/golang-migrate/migrate/cli
go build github.com/golang-migrate/migrate/database/postgres: no buildable Go source files in {GOPATH}/src/github.com/golang-migrate/migrate/database/postgres

If I run the go build with a tag other than postgres it works.

**Comment by aebie** [comment]
It seems to be the "// +build go1.9" line. I guess postgres requires go 1.9

**Comment by aebie** [comment]
It looks like the problem I am having is the "// +build go1.9" in the postgres.go file. Maybe document that postgres requires go 1.9?

**Comment by dhui** [comment]
Good sleuthing! I'm not sure if it's worth documenting the build constraints as the docs will probably  diverge from from the code. Also, we're planning to remove the build constraints, so there won't be anything to document in the future: https://github.com/golang-migrate/migrate/issues/60

I recommend you use the latest version of Go, since only the latest 2 major versions of Go are supported by Google (e.g. gets security fixes). https://golang.org/doc/devel/release.html#policy
To ease support, migrate only supports the supported versions of Go.

**Comment by dhui** [comment]
Also, migrate is using dep to manage dependencies. I'd use dep (or vgo) to manage your dependencies instead of `go get`.

The docs mentioning `go get` should be updated though...

**Comment by aebie** [comment]
Thanks, makes sense. I've upgraded to go 1.9 and now it works. Also, noticed another issue opened today that appears to be the same problem.

**Comment by maier-stefan** [comment]
@dhui I'm running in kind of the same issue. As I'm use currently a Dockerfile ```FROM golang:onbuild``` So am I right, that i can not do this anymore when using golang-migrate and have to start doing vendoring with ```dep```?

**Comment by dhui** [comment]
@maier-stefan Your issue seems unrelated to this one. Please open a new issue with more information (e.g. your full Dockerfile and the error message you're getting) and we'll proceed from there.
