### ISSUE TITLE
Please move cli directory to "cmd/migrate"

### ISSUE THREAD

**Issue by shuLhan** [golang-migrate/migrate#70]
Reason: so "go install" will create binary named "migrate" on $GOPATH/bin not "cli".

Thank you.

**Comment by dhui** [comment]
`go install` is not a [documented method for installing the cli](https://github.com/golang-migrate/migrate/blob/master/cli/README.md)

Keep in mind that `migrate` is also be used as a library so the current path structure is used so that imports look like `import "github.com/golang-migrate/migrate"`

I'm not sure if the breakage of backwards compatibility (if there are any builds relying on the current path) is worth the cosmetic change. Symlinks might help with backwards compatibility, but will be confusing for devs new to the project.

**Comment by dhui** [comment]
@vearutop Thanks for opening a PR. I like how you've moved the code up to another package that both binaries (orig and new CLIs) depend on.
