### ISSUE TITLE
v4.15.2 and mysql  Percona-XtraDB-Cluster failed, because of SERIALIZABLE transaction setting

### ISSUE THREAD

**Issue by ireinhart** [golang-migrate/migrate#768]
**Describe the Bug**
Since v4.15.2 I get the error
"Error 1105: Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING" at the start up of the tool, that do the migration.

Our Percona-XtraDB-Cluster based on mysql 5.7. The Percona Cluster disallow some functions, because of replication and some other stuff.

v4.15.1 and earlier versions works fine.

**Expected Behavior**
No error is thrown and migration works.

**Migrate Version**
v4.15.2

**Additional context**
Looks like the issue was introduce with

https://github.com/golang-migrate/migrate/compare/v4.15.1...v4.15.2#diff-824de966404b72d22606d8d155a7be8509ea01af07bd3728bc17df8447e38cbeL338-R344

> func (m *Mysql) SetVersion(version int, dirty bool) error {
	tx, err := m.conn.BeginTx(context.Background(), &sql.TxOptions{})
	tx, err := m.conn.BeginTx(context.Background(), &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return &database.Error{OrigErr: err, Err: "transaction start failed"}
	}

>	query := "TRUNCATE `" + m.config.MigrationsTable + "`"
	query := "DELETE FROM `" + m.config.MigrationsTable + "`"

**Comment by dhui** [comment]
Can you change `pxc_strict_mode` to `PERMISSIVE`?
https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#explicit-table-locking
Locking the migrations table is fine since it should only be used by the `migrate` tool.

Other options include:
1. make the isolation level configurable
2. use [upsert](https://dev.mysql.com/doc/refman/5.6/en/insert-on-duplicate.html). I'm not sure what version of mysql this was added. We currently [support](https://github.com/golang-migrate/migrate/blob/master/database/mysql/mysql_test.go#L42-L47) 5.5 to 8.0.
