### ISSUE TITLE
Multiple vulnerabilities reported by image scan

### ISSUE THREAD

**Issue by programmer04** [golang-migrate/migrate#802]
**Describe the Bug**
Multiple vulnerabilities were reported by image scan. I've scanned [migrate/migrate:v4.15.2](https://hub.docker.com/layers/migrate/migrate/migrate/v4.15.2/images/sha256-0ab1f7d276be40249640d34aad0978270c2c7654681c054a2e20b82ccf8d5dc6?context=explore) (current `latest`) with [Grype](https://github.com/anchore/grype) and I saw some vulnerabilities reported.

```
NAME                        INSTALLED  FIXED-IN   TYPE       VULNERABILITY   SEVERITY 
busybox                     1.32.1-r8  1.32.1-r9  apk        CVE-2022-30065  High      
google.golang.org/protobuf  v1.27.1               go-module  CVE-2015-5237   High      
google.golang.org/protobuf  v1.27.1    3.15.0     go-module  CVE-2021-22570  High      
libcrypto1.1                1.1.1n-r0  1.1.1q-r0  apk        CVE-2022-2097   High      
libssl1.1                   1.1.1n-r0  1.1.1q-r0  apk        CVE-2022-2097   High      
ssl_client                  1.32.1-r8  1.32.1-r9  apk        CVE-2022-30065  High      
zlib                        1.2.12-r0  1.2.12-r2  apk        CVE-2022-37434  Critical  
```
Some are related to the outdated base image [alpine:3.13.0](https://hub.docker.com/layers/alpine/library/alpine/3.13.0/images/sha256-0bc87802314f7c68e12bfbbc06574550e73b612f517c5ce706ff8efa40f6d3b1?context=explore) and some are specific for used Go packages. When the [migrate/migrate:v4.15.2](https://hub.docker.com/layers/migrate/migrate/migrate/v4.15.2/images/sha256-0ab1f7d276be40249640d34aad0978270c2c7654681c054a2e20b82ccf8d5dc6?context=explore) image is used in a regulated environment that kind of problem slows down releases, etc. because scanning is part of a CI/CI pipeline. It has to be carefully assessed.

**Steps to Reproduce**
Just scan the image with some tools for finding vulnerabilities.

**Expected Behavior**
No vulnerabilities are reported for the newest image.

**Additional context**
Updating Go, Alpine, and packages will fix it, but only for now. Security bugs are discovered all the time. 

As a more robust solution, I propose configuring [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) for keeping dependency like a base image and Go packages up to date. For Go packages, I advise enabling [dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) - security vulnerabilities will be reported automatically (unfortunately it doesn't work for images). 

I'll be happy to prepare PRs for the things proposed above. Please let me know what you think about it.

Similar issue https://github.com/golang-migrate/migrate/issues/777.

**Comment by dhui** [comment]
Thanks for reporting the issue! I'd merge a PR to update the alpine linux docker base image. Another approach that would prevent this issue from occurring would be to use a [scratch](https://hub.docker.com/_/scratch/) base image for the final docker image/build. The main issues with this are bundling certs and static builds.

We shouldn't be using protobufs directly so that's probably due to a dependency. If you can track that down and update the offending dependency, I'd also merge that PR.

**Comment by programmer04** [comment]
Yeah, using [scratch](https://hub.docker.com/_/scratch/) would be ideal, or at least using maybe something like [distroless](https://github.com/GoogleContainerTools/distroless). It requires some more testing thus I consider it the next step

**Comment by tspearconquest** [comment]
I've built and tested an image locally to fix these. I can fix everything but protobuf.

When scanning with grype with the `--only-fixed` flag, the protobufs do not appear, and I can confirm the same happens when I scan the image with Trivy with the `--ignore-unfixed` flag, so it seems there is no upstream fix for that one yet.

The others are all solved in the PR I'm about to submit.
