### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by meirbech** [golang-migrate/migrate#880]
**Is your feature request related to a problem? Please describe.**
there are many vulnerabilities with downstream dependencies that are fixed on master

**Describe the solution you'd like**
it will be great if you can release a new version with the updated dependencies 

**Describe alternatives you've considered**
not sure how else to solve it

**Comment by shota3506** [comment]
Thank you for providing this great library, maintainers!

I also ask you to publish new version because I want to use new feature released in cloud.google.com/go/spanner v1.28.0.
https://github.com/googleapis/google-cloud-go/releases/tag/spanner%2Fv1.32.0

**Comment by ry0suke17** [comment]
@dhui @Fontinalis Could you please release the latest version 🙏

**Comment by dhui** [comment]
For now, if you need updates, please use the master branch. You can [pin to a specific commit](https://go.dev/doc/modules/managing-dependencies#repo_identifier) if needed.

See also: https://github.com/golang-migrate/migrate/discussions/871#discussioncomment-5327215

I can't promise when the next release will be since I've had some other emergencies come up since the linked comment above.

**Comment by obalunenko** [comment]
@dhui Thank you for the release of [v4.16.0](https://github.com/golang-migrate/migrate/releases/tag/v4.16.0)
Thanks for the work you've done!

**Comment by dhui** [comment]
Thank you everyone for your patience! 🙏
As @obalunenko mentioned, [v4.16.0](https://github.com/golang-migrate/migrate/releases/tag/v4.16.0) was recently released. Now that the release process is fully automated, I'll be able to cut releases more frequently.
